import { describe, expect, it } from "vitest";
import {
  catalogNameMatchesSow,
  matchesSowPhase,
  normalizeSowText,
  rowMatchesWorkflowFilters,
  SOW_PHASE_1,
  SOW_PHASE_2,
} from "@/lib/sow-phases";

describe("sow-phases matching", () => {
  it("normalizes inch marks and dimension separators", () => {
    expect(normalizeSowText('BRAVADA SOFA 72" x 34" x 31" BH')).toBe(
      "BRAVADA SOFA 72 X 34 X 31",
    );
  });

  it("matches catalog names to SOW strings despite quote variance", () => {
    expect(
      catalogNameMatchesSow(
        "BRAVADA SOFA 72 x 34 x 31 BH",
        'BRAVADA SOFA 72" x 34" x 31" BH',
      ),
    ).toBe(true);
  });

  it("finds Phase 1 club chair against typical catalog wording", () => {
    expect(
      matchesSowPhase(
        'BRAVADA CLUB CHAIR 34" X 34" X 31" BH',
        SOW_PHASE_1,
      ),
    ).toBe(true);
  });

  it("keeps Phase 2 waterfall dining tables discoverable", () => {
    expect(
      matchesSowPhase(
        'WATERFALL TABLE (DINING HEIGHT) 36" x 72" x 30"',
        SOW_PHASE_2,
      ),
    ).toBe(true);
  });

  it("composes Phase 1 with auto-generated draft flag", () => {
    const row = {
      originalName: 'BRAVADA CLUB CHAIR 34" x 34" x 31" BH',
      hasAutoGeneratedDraft: true,
    };
    expect(
      rowMatchesWorkflowFilters(row, new Set(["phase1", "auto3d"])),
    ).toBe(true);
    expect(
      rowMatchesWorkflowFilters(
        { ...row, hasAutoGeneratedDraft: false },
        new Set(["phase1", "auto3d"]),
      ),
    ).toBe(false);
  });

  it("exports non-empty SOW lists", () => {
    expect(SOW_PHASE_1.length).toBeGreaterThan(80);
    expect(SOW_PHASE_2.length).toBeGreaterThan(100);
  });
});
