import { sku_mappings } from "@/server/db/schema";
import { type InferSelectModel } from "drizzle-orm";

export type SkuMappingRow = InferSelectModel<typeof sku_mappings>;

const KATANA_BASE_URL = "https://api.katanamrp.com/v1";

/**
 * Base fetch utility for Katana API.
 * Automatically attaches authentication and headers.
 * Throws structured errors on non-200 responses to trigger QA guardrails.
 */
async function fetchKatana(endpoint: string, options: RequestInit = {}) {
  const token = process.env.KATANA_API_KEY;
  if (!token) {
    throw new Error("KATANA_API_KEY is not configured in environment variables.");
  }

  const headers = {
    "Content-Type": "application/json",
    Authorization: `Bearer ${token}`,
    ...options.headers,
  };

  const url = `${KATANA_BASE_URL}${endpoint}`;
  
  try {
    const response = await fetch(url, {
      ...options,
      headers,
    });

    if (!response.ok) {
      let errorBody = "";
      try {
        errorBody = await response.text();
      } catch (e) {
        errorBody = "Failed to parse response body";
      }
      throw new Error(
        `[Katana API Error] ${response.status} ${response.statusText} for ${options.method} ${url}\nBody: ${errorBody}`
      );
    }

    return await response.json();
  } catch (error: any) {
    // If it's already our structured error, re-throw it.
    if (error.message.includes("[Katana API Error]")) {
      throw error;
    }
    // Otherwise, wrap unexpected network errors.
    throw new Error(`[Katana Network Error] ${error.message}`);
  }
}

/**
 * Maps a Supabase material row to Katana's POST /v1/materials structure.
 * Returns the variant.id generated by Katana.
 */
export async function upsertKatanaMaterial(row: SkuMappingRow): Promise<number> {
  const payload = {
    name: row.original_name || row.global_sku,
    category_name: row.category || "Uncategorized",
    type: "material",
    variants: [
      {
        sku: row.global_sku,
        purchase_price: row.base_cost ? Number(row.base_cost) : 0,
      },
    ],
  };

  const res = await fetchKatana("/materials", {
    method: "POST",
    body: JSON.stringify(payload),
  });

  if (res.variants && res.variants.length > 0) {
    return res.variants[0].id;
  }
  
  throw new Error("Katana material response did not contain any variants.");
}

/**
 * Maps a Supabase product row to Katana's POST /v1/products structure.
 * Returns the variant.id generated by Katana.
 */
export async function upsertKatanaProduct(row: SkuMappingRow, salesPrice: number = 0): Promise<number> {
  const payload = {
    name: row.original_name || row.global_sku,
    category_name: row.category || "Finished Good",
    type: "product",
    is_producible: true,
    is_purchasable: false,
    variants: [
      {
        sku: row.global_sku,
        sales_price: salesPrice,
      },
    ],
  };

  const res = await fetchKatana("/products", {
    method: "POST",
    body: JSON.stringify(payload),
  });

  if (res.variants && res.variants.length > 0) {
    return res.variants[0].id;
  }
  
  throw new Error("Katana product response did not contain any variants.");
}

/**
 * Creates a Recipe row (BOM) in Katana mapping a material variant to a product variant.
 */
export async function upsertKatanaRecipeRow(
  productVariantId: number,
  materialVariantId: number,
  quantity: number
): Promise<any> {
  const payload = {
    product_variant_id: productVariantId,
    ingredient_variant_id: materialVariantId,
    quantity: quantity,
  };

  return await fetchKatana("/recipes", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}
