import { sku_mappings } from "@/server/db/schema";
import { type InferSelectModel } from "drizzle-orm";

export type SkuMappingRow = InferSelectModel<typeof sku_mappings>;

const KATANA_BASE_URL = "https://api.katanamrp.com/v1";

/**
 * Base fetch utility for Katana API.
 * Automatically attaches authentication and headers.
 * Throws structured errors on non-200 responses to trigger QA guardrails.
 */
export async function fetchKatana(endpoint: string, options: RequestInit = {}) {
  const token =
    process.env.KATANA_PERSONAL_ACCESS_TOKEN?.trim() ??
    process.env.KATANA_API_KEY?.trim();
  if (!token) {
    throw new Error(
      "KATANA_PERSONAL_ACCESS_TOKEN (or KATANA_API_KEY) is not configured in environment variables.",
    );
  }

  const headers = {
    "Content-Type": "application/json",
    Authorization: `Bearer ${token}`,
    ...options.headers,
  };

  const base = (process.env.KATANA_API_BASE?.trim() || KATANA_BASE_URL).replace(
    /\/$/,
    "",
  );
  const url = `${base}${endpoint}`;
  
  try {
    const response = await fetch(url, {
      ...options,
      headers,
    });

    if (!response.ok) {
      let errorBody = "";
      try {
        errorBody = await response.text();
      } catch (e) {
        errorBody = "Failed to parse response body";
      }
      throw new Error(
        `[Katana API Error] ${response.status} ${response.statusText} for ${options.method} ${url}\nBody: ${errorBody}`
      );
    }

    return await response.json();
  } catch (error: any) {
    // If it's already our structured error, re-throw it.
    if (error.message.includes("[Katana API Error]")) {
      throw error;
    }
    // Otherwise, wrap unexpected network errors.
    throw new Error(`[Katana Network Error] ${error.message}`);
  }
}

/**
 * Maps a Supabase material row to Katana's POST /v1/materials structure.
 * Returns the variant.id generated by Katana.
 */
export async function upsertKatanaMaterial(row: SkuMappingRow): Promise<number> {
  const payload: any = {
    name: row.original_name || row.global_sku,
    category_name: row.category || "Uncategorized",
    variants: [
      {
        sku: row.global_sku,
        purchase_price: row.base_cost ? Number(row.base_cost) : 0,
      },
    ],
  };

  const attrs = row.attributes as Record<string, any> | null;
  if (attrs && attrs.description) {
    payload.additional_info = String(attrs.description);
  }

  const res = await fetchKatana("/materials", {
    method: "POST",
    body: JSON.stringify(payload),
  });

  if (res.variants && res.variants.length > 0) {
    return res.variants[0].id;
  }
  
  throw new Error("Katana material response did not contain any variants.");
}

/**
 * Maps a Supabase product row to Katana's POST /v1/products structure.
 * Returns the variant.id generated by Katana.
 */
export async function upsertKatanaProduct(row: SkuMappingRow, salesPrice: number = 0): Promise<number> {
  const payload: any = {
    name: row.original_name || row.global_sku,
    category_name: row.category || "Finished Good",
    is_producible: true,
    is_purchasable: false,
    variants: [
      {
        sku: row.global_sku,
        sales_price: salesPrice,
      },
    ],
  };

  const attrs = row.attributes as Record<string, any> | null;
  if (attrs && attrs.description) {
    payload.additional_info = String(attrs.description);
  }

  const res = await fetchKatana("/products", {
    method: "POST",
    body: JSON.stringify(payload),
  });

  if (res.variants && res.variants.length > 0) {
    return res.variants[0].id;
  }
  
  throw new Error("Katana product response did not contain any variants.");
}

/**
 * Creates a Recipe row (BOM) in Katana mapping a material variant to a product variant.
 */
export async function upsertKatanaRecipeRow(
  productVariantId: number,
  materialVariantId: number,
  quantity: number
): Promise<any> {
  const payload = {
    product_variant_id: productVariantId,
    ingredient_variant_id: materialVariantId,
    quantity: quantity,
  };

  return await fetchKatana("/recipes", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

/**
 * Archives a Katana variant by its SKU or ID.
 */
export async function archiveKatanaVariant(variantId: number): Promise<void> {
  // In a real implementation, you'd PATCH the variant or material/product status
  await fetchKatana(`/variants/${variantId}`, {
    method: "PATCH",
    body: JSON.stringify({ is_active: false }),
  });
}

function unwrapList<T>(payload: unknown): T[] {
  if (Array.isArray(payload)) return payload as T[];
  if (payload && typeof payload === "object" && "data" in payload) {
    const data = (payload as { data?: unknown }).data;
    if (Array.isArray(data)) return data as T[];
  }
  return [];
}

export type KatanaVariantHit = {
  id: number;
  sku: string;
  type: string;
  product_id: number | null;
  material_id: number | null;
};

export async function getKatanaVariantBySku(
  sku: string,
): Promise<KatanaVariantHit | null> {
  const needle = sku.trim().toUpperCase();
  const res = await fetchKatana(
    `/variants?sku=${encodeURIComponent(needle)}&limit=5`,
  );
  const rows = unwrapList<Record<string, unknown>>(res);
  for (const row of rows) {
    const hitSku = String(row.sku ?? "").toUpperCase();
    if (hitSku !== needle) continue;
    return {
      id: Number(row.id),
      sku: String(row.sku ?? ""),
      type: String(row.type ?? ""),
      product_id: row.product_id == null ? null : Number(row.product_id),
      material_id: row.material_id == null ? null : Number(row.material_id),
    };
  }
  return null;
}

export type KatanaBomRowHit = {
  id: string | number | null;
  product_variant_id: number | null;
  ingredient_variant_id: number | null;
  quantity: number | null;
  notes: string | null;
  ingredient_sku?: string | null;
};

export async function listKatanaBomRows(
  productVariantId: number,
): Promise<KatanaBomRowHit[]> {
  const all: KatanaBomRowHit[] = [];
  for (let page = 1; page <= 20; page += 1) {
    const res = await fetchKatana(
      `/bom_rows?product_variant_id=${productVariantId}&limit=250&page=${page}`,
    );
    const rows = unwrapList<Record<string, unknown>>(res);
    const mapped = rows
      .map((row) => ({
        id: (row.id as string | number | null) ?? null,
        product_variant_id:
          row.product_variant_id == null ? null : Number(row.product_variant_id),
        ingredient_variant_id:
          row.ingredient_variant_id == null
            ? null
            : Number(row.ingredient_variant_id),
        quantity: row.quantity == null ? null : Number(row.quantity),
        notes: typeof row.notes === "string" ? row.notes : null,
        ingredient_sku:
          typeof row.ingredient_sku === "string" ? row.ingredient_sku : null,
      }))
      .filter((row) => row.product_variant_id === productVariantId);
    all.push(...mapped);
    if (rows.length < 250) break;
  }
  return all;
}

export async function listKatanaRecipeRows(
  productVariantId: number,
): Promise<KatanaBomRowHit[]> {
  const res = await fetchKatana(
    `/recipes?product_variant_id=${productVariantId}&limit=250&page=1`,
  );
  const rows = unwrapList<Record<string, unknown>>(res);
  return rows
    .map((row) => ({
      id: (row.id as string | number | null) ?? null,
      product_variant_id:
        row.product_variant_id == null ? null : Number(row.product_variant_id),
      ingredient_variant_id:
        row.ingredient_variant_id == null
          ? null
          : Number(row.ingredient_variant_id),
      quantity: row.quantity == null ? null : Number(row.quantity),
      notes: typeof row.notes === "string" ? row.notes : null,
      ingredient_sku:
        typeof row.ingredient_sku === "string" ? row.ingredient_sku : null,
    }))
    .filter((row) => row.product_variant_id === productVariantId);
}

export type KatanaOperationHit = {
  id: number | null;
  product_variant_id: number | null;
  operation_name: string;
  resource_name: string;
  type: string | null;
};

export async function listKatanaOperations(
  productVariantId: number,
): Promise<KatanaOperationHit[]> {
  const all: KatanaOperationHit[] = [];
  for (let page = 1; page <= 20; page += 1) {
    const res = await fetchKatana(
      `/product_operation_rows?product_variant_id=${productVariantId}&limit=250&page=${page}`,
    );
    const rows = unwrapList<Record<string, unknown>>(res);
    const mapped = rows
      .map((row) => ({
        id: row.id == null ? null : Number(row.id),
        product_variant_id:
          row.product_variant_id == null ? null : Number(row.product_variant_id),
        operation_name: String(row.operation_name ?? row.name ?? ""),
        resource_name: String(row.resource_name ?? row.resource ?? ""),
        type: typeof row.type === "string" ? row.type : null,
      }))
      .filter(
        (row) =>
          row.product_variant_id == null ||
          row.product_variant_id === productVariantId,
      );
    all.push(...mapped);
    if (rows.length < 250) break;
  }
  if (all.length > 0) {
    return all.filter(
      (row) =>
        row.product_variant_id == null ||
        row.product_variant_id === productVariantId,
    );
  }
  return all;
}

