// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by scripts/sync-topology-nodes.ts

export const LIVE_IDS = {
  GHL: {
    stages: {
      AZ_GATE_1: "a43ddce2-44e8-4f0a-b506-d927d50aee4a",
      CA_GATE_1: "2975b751-a11d-480e-a2db-56f5ac36d976"
    },
    pipelines: {
      Commercials: "LWCJ4zz6MEwBRL1QBht5",
      CRM_Segmentation: "RxjrS9hBizzwQ91NBTYm",
      Invoice: "KyT0Jqbw7pbYkYdZPLoa",
      Leads: "H5lHuXVpTwXLCAtDEkIA",
      Manufacturing: "ZMhyCOpo9M8KxRhaoteN",
      Scottsdale___Sales__AZ_: "hu9VUgAxItleNsiZRIYn",
      Solana_Beach___Sales__CA_: "PaPMUtPGBD9ZQMNNNDt3",
      Trade: "qLYOVUkHqk4cJZz6Uitv",
      Warranty_Claims: "hYaub2RFeFkmc9ZKdvc0"
    }
  },
  KATANA: {
    raw: "Empty"
  }
};
