/**
 * Shareholder / training story cards keyed by nodeId, nodeId::stageId, or storyKey.
 * Expand as ops research lands — never remove keys; only enrich.
 */

import type { JourneyId } from "./sequences";

export type StoryCard = {
  title: string;
  customer: string;
  owner: string;
  system: string;
  dwell: string;
  unlocks: string;
  zone?: string;
};

function key(nodeId: string, stageId?: string | null) {
  return stageId ? `${nodeId}::${stageId}` : nodeId;
}

const STORIES: Record<string, StoryCard> = {
  "traffic-meta": {
    title: "Demand enters the brand",
    customer: "Sees an ad or design post and starts a conversation.",
    owner: "Marketing",
    system: "UTM / click IDs land in session; GHL can attribute the lead.",
    dwell: "Instant",
    unlocks: "A chat or form that creates a CRM opportunity.",
    zone: "Omnichannel",
  },
  "chan-webchat": {
    title: "Live conversation on ccpatio.com",
    customer: "Asks about sizing, fabrics, or showroom visits.",
    owner: "Front desk / Sales",
    system: "Web chat routes into the GHL Unified Inbox.",
    dwell: "Minutes",
    unlocks: "Tagged opportunity in the right pipeline.",
    zone: "Channel",
  },
  "chan-phone": {
    title: "Inbound call (Trade / Commercial)",
    customer: "Designer or developer calls to open an account or project.",
    owner: "Sales / Trade desk",
    system: "Twilio/GHL call route → Unified Inbox → Trade pipeline.",
    dwell: "Minutes–hours",
    unlocks: "Trade application or Sales opportunity.",
    zone: "Channel",
  },
  "chan-whatsapp": {
    title: "WhatsApp service thread",
    customer: "Sends photos of damage or a serial-number question.",
    owner: "Service",
    system: "WhatsApp Business → GHL inbox → Warranty pipeline.",
    dwell: "Minutes",
    unlocks: "Claim discovery card.",
    zone: "Channel",
  },
  "ghl-hub": {
    title: "GHL Unified Inbox (the router)",
    customer: "Doesn’t see this — internal brain of intake.",
    owner: "Ops / Sales admin",
    system: "Tags (retail_az, commercial, warranty) and spawns the card.",
    dwell: "Seconds",
    unlocks: "Correct pipeline: Leads, Trade, or Warranty.",
    zone: "Aggregator",
  },
  "leads-pipe::lead-new": {
    title: "New / uncontacted lead",
    customer: "Waiting for a human reply after the first touch.",
    owner: "Sales",
    system: "Leads pipeline card; SLA clock starts.",
    dwell: "Hours (first-touch SLA)",
    unlocks: "Website Order Form or showroom visit.",
    zone: "Retail Leads",
  },
  "leads-pipe::lead-website": {
    title: "Website Order Form (CRM gate)",
    customer: "Submits project details online.",
    owner: "Sales",
    system: "Lead qualifies → Scottsdale or Solana Beach Sales opportunity.",
    dwell: "Hours–days of nurture before this",
    unlocks: "Showroom / design sales process — not factory yet.",
    zone: "Retail Leads",
  },
  "trade-pipe::trade-app": {
    title: "Trade application submitted",
    customer: "Designer/developer requests wholesale or project pricing.",
    owner: "Trade desk",
    system: "Application card; credit/terms review is human.",
    dwell: "Days",
    unlocks: "Approved account → CA Sales opportunity.",
    zone: "Trade",
  },
  "trade-pipe::trade-approved": {
    title: "Trade account approved",
    customer: "Can now specify CCPatio on commercial projects.",
    owner: "Trade desk / Sales CA",
    system: "Commercial tag + Solana Beach Sales swimlane.",
    dwell: "Same day as approval",
    unlocks: "On-site / design cycle on Sales CA.",
    zone: "Trade",
  },
  "sales-az::az-onsite": {
    title: "On-site scheduled",
    customer: "Expects a field visit or measurement appointment.",
    owner: "Sales / Field (.D)",
    system: "CRM stage only — no middleware mutations.",
    dwell: "Days (calendar)",
    unlocks: "SketchUp / engineering work.",
    zone: "Sales AZ",
  },
  "sales-az::az-sketchup-needed": {
    title: "Design bridge — SketchUp needed",
    customer: "Waiting on a 3D concept that matches their space.",
    owner: "Design / Engineering",
    system: "Human BOM + dimensions; CAD/CAM packets prepared later.",
    dwell: "Days–weeks",
    unlocks: "Proposal with real SKUs and finishes.",
    zone: "Sales AZ",
  },
  "sales-az::az-sketchup-done": {
    title: "SketchUp complete — design locked for proposal",
    customer: "Sees a 3D that they can react to.",
    owner: "Design + Sales",
    system: "Packet returns to Sales; SKUs not frozen until finalize.",
    dwell: "Hours–days of review",
    unlocks: "Proposal Given.",
    zone: "Sales AZ",
  },
  "sales-az::az-proposal": {
    title: "Proposal given",
    customer: "Reviews pricing, fabrics, and lead time.",
    owner: "Sales",
    system: "CRM document / e-sign; still no factory webhook.",
    dwell: "Days (customer decision)",
    unlocks: "Finalize finishes + deposit.",
    zone: "Sales AZ",
  },
  "sales-az::az-finalize": {
    title: "Finalize finishes",
    customer: "Picks powder, fabric, and configuration details.",
    owner: "Sales",
    system: "SKU freeze in the packet that Produce FO will send.",
    dwell: "Hours–days",
    unlocks: "Produce Factory Order stage in CRM.",
    zone: "Sales AZ",
  },
  "sales-az::az-produce": {
    title: "Produce Factory Order (Gate 1 prep)",
    customer: "FO is drafted; factory queue is prepared.",
    owner: "Sales / Ops",
    system: "GHL stage move creates the FO record — deposit must clear before Client Approval.",
    dwell: "Hours–days in CRM",
    unlocks: "Omnichannel Payment Gateway (QBO link or Clover swipe).",
    zone: "Sales AZ",
  },
  "sales-az::az-approval": {
    title: "Client Approval — sign-off & deposit clearance",
    customer: "Final sign-off before factory webhook releases.",
    owner: "Sales",
    system:
      "Deposit cleared + e-sign complete → Produce + Won webhook → Ingress outbox → Katana MO.",
    dwell: "Hours–days (customer action)",
    unlocks: "Middleware Gate 1 · factory physical build.",
    zone: "Sales AZ",
  },
  "sales-az::az-delivered": {
    title: "Sales → 08. Delivered",
    customer: "Order is complete in the CRM they were sold from.",
    owner: "Sales / Finance",
    system: "Stage move after Delivered + QBO path; Clover miss does not block this.",
    dwell: "Minutes after financial clearance",
    unlocks: "Post-care sequences.",
    zone: "Sales AZ",
  },
  "sales-ca::ca-onsite": {
    title: "On-site scheduled (Solana Beach)",
    customer: "Site walk or showroom appointment for a commercial project.",
    owner: "Sales CA / Field",
    system: "CRM stage only.",
    dwell: "Days (calendar)",
    unlocks: "SketchUp / engineering.",
    zone: "Sales CA",
  },
  "sales-ca::ca-sketchup-needed": {
    title: "Design bridge — SketchUp needed (CA)",
    customer: "Waiting on drawings that match the job site.",
    owner: "Design / Engineering",
    system: "Same CAD/CAM path as retail; commercial SKUs.",
    dwell: "Days–weeks",
    unlocks: "Proposal.",
    zone: "Sales CA",
  },
  "sales-ca::ca-sketchup-done": {
    title: "SketchUp complete (CA)",
    customer: "Reviews the 3D / shop intent.",
    owner: "Design + Sales CA",
    system: "Packet returns to Solana Beach Sales.",
    dwell: "Hours–days",
    unlocks: "Proposal Given.",
    zone: "Sales CA",
  },
  "sales-ca::ca-proposal": {
    title: "Proposal given (CA)",
    customer: "Trade/commercial pricing and lead time on the table.",
    owner: "Sales CA",
    system: "CRM docs; no factory webhook yet.",
    dwell: "Days",
    unlocks: "Finalize finishes.",
    zone: "Sales CA",
  },
  "sales-ca::ca-finalize": {
    title: "Finalize finishes (CA)",
    customer: "Locks spec for the purchase order.",
    owner: "Sales CA",
    system: "SKU freeze for Produce FO payload.",
    dwell: "Hours–days",
    unlocks: "Produce Factory Order stage in CRM.",
    zone: "Sales CA",
  },
  "sales-ca::ca-produce": {
    title: "Produce Factory Order (Solana Beach)",
    customer: "FO is drafted; factory queue is prepared.",
    owner: "Sales CA / Ops",
    system: "GHL stage move — deposit must clear before Client Approval.",
    dwell: "Hours–days in CRM",
    unlocks: "Omnichannel Payment Gateway (QBO link or Clover swipe).",
    zone: "Sales CA",
  },
  "sales-ca::ca-approval": {
    title: "Client Approval — sign-off & deposit clearance (CA)",
    customer: "Final sign-off before factory webhook releases.",
    owner: "Sales CA",
    system:
      "Deposit cleared + e-sign → Produce + Won webhook → Ingress → Katana MO.",
    dwell: "Hours–days (customer action)",
    unlocks: "Middleware Gate 1 · factory physical build.",
    zone: "Sales CA",
  },
  "sales-ca::ca-delivered": {
    title: "Sales CA → Delivered",
    customer: "Project is closed in the selling pipeline.",
    owner: "Sales CA / Finance",
    system: "Stage move after Katana Delivered + QBO.",
    dwell: "Minutes",
    unlocks: "Post-care / account manager follow-up.",
    zone: "Sales CA",
  },
  "field-survey": {
    title: "On-site lidar / survey",
    customer: "Someone is measuring their space.",
    owner: "Field (.D)",
    system: "Dimensions feed SketchUp; not a middleware mutation.",
    dwell: "Hours on site + processing",
    unlocks: "Accurate 3D.",
    zone: "Design",
  },
  sketchup: {
    title: "SketchUp 3D modeling",
    customer: "Waiting for a visual they can approve.",
    owner: "Design",
    system: "Human modeling; tube cut schedules follow.",
    dwell: "Days",
    unlocks: "Chop saw cut lists + BOM.",
    zone: "Design",
  },
  "cut-lists": {
    title: "Tube cut schedules & miter angles",
    customer: "Invisible — chop saw traveler is being prepared.",
    owner: "Engineering",
    system: "Manual chop saw schedules — no CNC laser nesting.",
    dwell: "Hours–days",
    unlocks: "BOM assembly packet.",
    zone: "Cut Lists",
  },
  "bom-packet": {
    title: "BOM assembly packet",
    customer: "Spec is becoming real SKUs and finishes.",
    owner: "Engineering / Sales",
    system: "Shop drawings + frozen SKU list for Produce FO.",
    dwell: "Hours–days",
    unlocks: "SketchUp Done in Sales → proposal.",
    zone: "Cut Lists",
  },
  "qbo-deposit-link": {
    title: "QBO payment link — 50% deposit",
    customer: "Receives emailed invoice link to pay deposit.",
    owner: "Sales / Finance",
    system: "QuickBooks Online payment link clears into Omnichannel Payment Gateway.",
    dwell: "Hours–days",
    unlocks: "Payment gateway → Client Approval.",
    zone: "Deposit",
  },
  "clover-showroom": {
    title: "Clover showroom terminal — 50% deposit",
    customer: "Swipes card in showroom for deposit.",
    owner: "Sales",
    system: "In-store Clover POS → same Omnichannel Payment Gateway.",
    dwell: "Minutes",
    unlocks: "Payment gateway → Client Approval.",
    zone: "Deposit",
  },
  "payment-gateway": {
    title: "Omnichannel payment gateway",
    customer: "Deposit is confirmed — order can release to factory.",
    owner: "Finance / Ops",
    system: "Either QBO link or Clover swipe must clear before 07.S Client Approval.",
    dwell: "Seconds once paid",
    unlocks: "07.S Client Approval → Ingress webhook.",
    zone: "Gate 0.5",
  },
  "inventory-alloc": {
    title: "Inventory allocation check",
    customer: "Invisible — materials are being reserved.",
    owner: "Factory / Purchasing",
    system: "Katana stock check: in-stock fast-tracks to chop saw; backorder enters 10-day procurement.",
    dwell: "Hours",
    unlocks: "Chop saw (in-stock) or procurement wait (backorder).",
    zone: "Materials",
  },
  "procurement-wait": {
    title: "Procurement wait loop",
    customer: "Lead time buffer while extrusion stock is ordered.",
    owner: "Purchasing",
    system: "10-day SLA buffer · GHL Manufacturing → Purchasing / Receiving sync.",
    dwell: "Up to 10 calendar days",
    unlocks: "Tube metal stock & staging.",
    zone: "Purchasing",
  },
  "outsourced-accessories": {
    title: "Outsourced accessories hold",
    customer: "Umbrellas and pool chairs wait for in-house frames.",
    owner: "Purchasing / Assembly",
    system: "Bypasses fabrication pods — merges at Component Assembly / Marriage.",
    dwell: "Weeks (parallel to metal build)",
    unlocks: "Marriage when metal frame is ready.",
    zone: "Bypass",
  },
  "dispatch-routes::dispatch-box": {
    title: "CCPatio box truck (< 500 mi)",
    customer: "Local white-glove delivery scheduled.",
    owner: "Logistics",
    system: "In-house box truck route · Samsara / Onfleet.",
    dwell: "Days until slot",
    unlocks: "Delivery → QBO final invoice.",
    zone: "Logistics",
  },
  "dispatch-routes::dispatch-3pl": {
    title: "3PL freight dispatch (> 500 mi)",
    customer: "National freight carrier scheduled.",
    owner: "Logistics",
    system: "Third-party freight · same delivery + invoice path.",
    dwell: "Days",
    unlocks: "Delivery → QBO final invoice.",
    zone: "Logistics",
  },
  "dispatch-routes::dispatch-willcall": {
    title: "Customer will-call / pickup",
    customer: "Picks up finished goods at factory.",
    owner: "Logistics / Sales",
    system: "Will-call route · still flows through QBO invoice + ledger reconciled.",
    dwell: "Scheduled window",
    unlocks: "Delivery sign-off → treasury.",
    zone: "Logistics",
  },
  "mfg-pipe::mfg-production": {
    title: "Production in progress (mirror pulse)",
    customer: "Invisible — CRM shows active factory work.",
    owner: "Ops / Factory",
    system: "Katana → GHL Manufacturing sync when frame enters Fabrication Pod.",
    dwell: "Weeks",
    unlocks: "Ready for Delivery when QC passes.",
    zone: "Manufacturing mirror",
  },
  "produce-az": {
    title: "AZ Produce + Won trigger",
    customer: "Sold — factory is now responsible.",
    owner: "Ops",
    system: "GHL webhook body that Ingress HMAC-checks.",
    dwell: "Seconds",
    unlocks: "Outbox + Katana MO.",
    zone: "Trigger",
  },
  "produce-ca": {
    title: "CA Produce + Won trigger",
    customer: "Commercial order released.",
    owner: "Ops",
    system: "Same Gate 1 webhook; franchise field routes later QBO.",
    dwell: "Seconds",
    unlocks: "Ingress.",
    zone: "Trigger",
  },
  "produce-warranty": {
    title: "Warranty Produce FO trigger",
    customer: "Remake/repair is authorized.",
    owner: "Service / Ops",
    system: "Gate 1 without the sales design loop.",
    dwell: "Seconds",
    unlocks: "Factory remake traveler.",
    zone: "Trigger",
  },
  ingress: {
    title: "Middleware ingress (zero data loss)",
    customer: "Invisible — reliability layer.",
    owner: "Engineering",
    system: "HMAC, Postgres outbox, Redis dedupe, Inngest CCR leases.",
    dwell: "Seconds",
    unlocks: "Exactly-once factory dispatch under retries.",
    zone: "Edge",
  },
  redis: {
    title: "Redis L1 dedupe (fail-open)",
    customer: "Invisible.",
    owner: "Engineering",
    system: "15m TTL key. If Redis is down, traffic continues (fail-open).",
    dwell: "Milliseconds (or timeout)",
    unlocks: "Postgres outbox remains source of truth.",
    zone: "Dedupe",
  },
  postgres: {
    title: "Postgres outbox & saga",
    customer: "Invisible.",
    owner: "Engineering",
    system: "frozen_sku, CCR claims, idempotent jobs — never lost on retry.",
    dwell: "Seconds",
    unlocks: "Inngest lease.",
    zone: "State",
  },
  inngest: {
    title: "Inngest Stateful CCR",
    customer: "Invisible — order is safely moving to the factory.",
    owner: "System / API",
    system:
      "Inngest CCR worker acquires lease. Prevents duplicate Katana MO creation during webhook retries.",
    dwell: "Seconds–minutes if retrying",
    unlocks: "Katana MO + GHL Manufacturing mirror fan-out.",
    zone: "Execution",
  },
  "mfg-pipe::mfg-new": {
    title: "GHL Manufacturing — New FO / New SO",
    customer: "Invisible — CRM manufacturing card appears once the MO exists.",
    owner: "System / API",
    system: "Katana → GHL Manufacturing bi-dir mirror: New FO / New SO stage.",
    dwell: "Seconds after MO create",
    unlocks: "Inventory allocation check on the factory floor.",
    zone: "GHL Manufacturing Mirror",
  },
  "mfg-pipe::mfg-purchasing": {
    title: "GHL Manufacturing — Purchasing / Receiving",
    customer: "Invisible — materials status syncs to the CRM mirror.",
    owner: "System / API",
    system:
      "Katana purchasing/receiving pulse → GHL Manufacturing Purchasing stage.",
    dwell: "Seconds (sync)",
    unlocks: "Chop saw / fabrication when stock clears.",
    zone: "GHL Manufacturing Mirror",
  },
  katana: {
    title: "Katana = physical truth",
    customer: "Order is now a manufacturing job.",
    owner: "Factory",
    system: "MO created with Idempotency-Key; GHL Manufacturing only mirrors.",
    dwell: "Weeks of production",
    unlocks: "Work centers → QC → Ready for Delivery.",
    zone: "Factory API",
  },
  "work-centers::wc-tube-stock": {
    title: "Tube metal stock & staging",
    customer: "Marine-grade aluminum extrusion is being kitted.",
    owner: "Factory · Materials",
    system: "Raw extrusion inventory pulled from tube stock racks.",
    dwell: "Days in queue",
    unlocks: "Chop saw cut & miter station.",
    zone: "Shop floor",
  },
  "work-centers::wc-chop-saw": {
    title: "Chop saw cut & miter station",
    customer: "Extrusions are cut to length — no CNC laser or mandrel bending.",
    owner: "Factory · Fabrication",
    system: "Precision chop saws: straight cuts, angles, miters, deburring.",
    dwell: "Hours",
    unlocks: "Rolling cart parts staging.",
    zone: "Shop floor",
  },
  "work-centers::wc-cart-parts": {
    title: "Rolling cart parts staging",
    customer: "Cut tube profiles are kitted onto mobile carts.",
    owner: "Factory · Materials",
    system: "Cart-based WIP between cut station and fabrication pods.",
    dwell: "Hours",
    unlocks: "Fabrication pod (3-man team).",
    zone: "Shop floor",
  },
  "work-centers::wc-tack": {
    title: "4A · Tack welder station",
    customer: "Frame is jig-clamped and tacked.",
    owner: "Factory · Fabrication Pod",
    system: "First of three pod stations — tack before full weld-out.",
    dwell: "Hours",
    unlocks: "Weld out station.",
    zone: "Shop floor",
  },
  "work-centers::wc-weld-out": {
    title: "4B · Weld out station",
    customer: "Structural bead welding completes the frame.",
    owner: "Factory · Fabrication Pod",
    system: "Full structural welds; Gate A inspects dimension + weld quality next.",
    dwell: "Hours–days",
    unlocks: "Grinder station → component marriage.",
    zone: "Shop floor",
  },
  "work-centers::wc-grinder": {
    title: "4C · Grinder station",
    customer: "Weld seams are smoothed and prepped.",
    owner: "Factory · Fabrication Pod",
    system: "Weld seam smoothing before sub-frame marriage.",
    dwell: "Hours",
    unlocks: "Component assembly & marriage.",
    zone: "Shop floor",
  },
  "work-centers::wc-marriage": {
    title: "Component assembly & marriage",
    customer: "Modular sub-frames join into finished builds.",
    owner: "Factory · Assembly",
    system: "Marriage of pod outputs before Gate A weld/dim check.",
    dwell: "Hours–days",
    unlocks: "QC Gate A.",
    zone: "Shop floor",
  },
  "work-centers::wc-cart-blast": {
    title: "Rolling cart staging to sandblast",
    customer: "Completed build rolled to surface prep.",
    owner: "Factory · Finishing",
    system: "Cart WIP between marriage and sandblast bay.",
    dwell: "Hours",
    unlocks: "Surface prep & sandblaster.",
    zone: "Shop floor",
  },
  "work-centers::wc-sandblast": {
    title: "Surface prep & sandblaster",
    customer: "Frame is media-blasted for coating adhesion.",
    owner: "Factory · Finishing",
    system: "Prep quality drives Gate B adhesion later.",
    dwell: "Hours",
    unlocks: "Powder coat & curing oven.",
    zone: "Shop floor",
  },
  "work-centers::wc-powder": {
    title: "Powder coat & curing oven",
    customer: "Frame finish is being applied and cured.",
    owner: "Factory · Coatings",
    system: "Shop floor station; QC Gate B follows adhesion/DFT checks.",
    dwell: "Hours–days in queue + cure cycle",
    unlocks: "Custom upholstery after QC pass.",
    zone: "Shop floor",
  },
  "work-centers::wc-upholstery": {
    title: "Custom upholstery & cushion sewing",
    customer: "Cushions and covers are being made to spec.",
    owner: "Factory · Soft goods",
    system: "Parallel to metal once frames pass Gate B.",
    dwell: "Hours–days",
    unlocks: "Final assembly, glides & hardware.",
    zone: "Shop floor",
  },
  "work-centers::wc-final": {
    title: "Final assembly, glides & hardware",
    customer: "Pieces become the finished suite.",
    owner: "Factory · Assembly",
    system: "Traveler complete before Gate C photo log.",
    dwell: "Hours–days",
    unlocks: "QC Gate C → Ready for Delivery.",
    zone: "Shop floor",
  },
  "qc-gates::qc-a": {
    title: "Gate A — weld / dimension",
    customer: "Quality is being proven before coating.",
    owner: "QC",
    system: "Fail → NCR freeze + remake at weld. Pass → blast/powder.",
    dwell: "Hours",
    unlocks: "Next work center or NCR loop.",
    zone: "QC",
  },
  "qc-gates::qc-b": {
    title: "Gate B — DFT / adhesion",
    customer: "Finish quality is locked.",
    owner: "QC",
    system: "Coating thickness + adhesion; fail returns to finishing.",
    dwell: "Hours",
    unlocks: "Upholstery / assembly.",
    zone: "QC",
  },
  "qc-gates::qc-c": {
    title: "Gate C — pre-pack photo log",
    customer: "Quality locked before shipping.",
    owner: "QC",
    system: "360° photos can attach to GHL; NCR freezes remakes if fail.",
    dwell: "Hours",
    unlocks: "Ready for Delivery / logistics scheduling.",
    zone: "QC",
  },
  "mfg-pipe::mfg-ready": {
    title: "Ready for Delivery (mirror)",
    customer: "Product is waiting on a scheduled route.",
    owner: "Logistics / Factory",
    system: "GHL Manufacturing mirrors Katana — not the system of record.",
    dwell: "Days until dispatch slot",
    unlocks: "Dispatch → white-glove delivery.",
    zone: "Manufacturing mirror",
  },
  "mfg-pipe::mfg-delivered": {
    title: "Manufacturing Delivered | Rejected",
    customer: "Either on the way — or a reject/NCR is in play.",
    owner: "Factory / QC",
    system: "Mirror stage; Rejected is the NCR holding pattern.",
    dwell: "Hours–days until disposition",
    unlocks: "Rework or logistics.",
    zone: "Manufacturing mirror",
  },
  dispatch: {
    title: "Dispatch scheduling",
    customer: "Gets a delivery window.",
    owner: "Logistics",
    system: "Route planning after Ready for Delivery.",
    dwell: "Days (calendar)",
    unlocks: "White-glove delivery.",
    zone: "Logistics",
  },
  delivery: {
    title: "White-glove delivery",
    customer: "Furniture placed and signed off on site.",
    owner: "Logistics",
    system: "Katana Delivered event starts financial clearance (retail/trade).",
    dwell: "Scheduled route day",
    unlocks: "QBO invoice + Clover deposit match — warranty often skips QBO.",
    zone: "Logistics",
  },
  qbo: {
    title: "Financial clearance — QBO invoice",
    customer: "Receives formal invoice / remaining balance path.",
    owner: "Finance",
    system: "OAuth mutex; inv_${opportunity_id}; never blocked by Clover miss.",
    dwell: "Minutes (systems) after Delivered",
    unlocks: "Deposit reconciliation; Sales → 08. Delivered.",
    zone: "Treasury",
  },
  clover: {
    title: "Clover POS fuzzy match",
    customer: "Deposit already paid at POS or link.",
    owner: "Finance",
    system: "Match by amount/window/location; unmatched → DLQ, invoice stays.",
    dwell: "Minutes–days if manual recon",
    unlocks: "Ledger closed; post-care marketing loop.",
    zone: "Treasury",
  },
  reconciled: {
    title: "Ledger reconciled",
    customer: "Books match cash — journey terminal within the 56-day max SLA.",
    owner: "Finance",
    system: "Happy-path close after Clover match (or manual recon).",
    dwell: "+2 days · journey terminal (see Timeline)",
    unlocks: "Post-care.",
    zone: "Treasury",
  },
  postcare: {
    title: "Post-care & warranty registry",
    customer: "SMS passport, NPS, care guide, seasonal follow-ups.",
    owner: "Marketing / Service",
    system: "GHL sequences; warranty linked to serial number.",
    dwell: "Day 0 / 3 / 7 / 30 cadence",
    unlocks: "Reviews, referrals, long-term brand loyalty.",
    zone: "Post-care",
  },
  "warranty-pipe::warranty-discovery": {
    title: "Warranty discovery",
    customer: "Photos and serial are being reviewed.",
    owner: "Service",
    system: "Claim card; no factory until Produce FO.",
    dwell: "Days",
    unlocks: "Approval / color selection.",
    zone: "Warranty",
  },
  "warranty-pipe::warranty-approved": {
    title: "Claim approved — selecting colors",
    customer: "Picks finish/fabric for the remake.",
    owner: "Service",
    system: "Still CRM; Produce FO is the automation gate.",
    dwell: "Days",
    unlocks: "Warranty Produce FO.",
    zone: "Warranty",
  },
  "warranty-pipe::warranty-produce": {
    title: "Warranty Produce FO",
    customer: "Approved claim moving to remake/repair.",
    owner: "Service",
    system: "Skips sales design loop; middleware → factory; often skips QBO.",
    dwell: "Days after claim approval",
    unlocks: "Factory remake traveler → Claim Closed.",
    zone: "Gate 1",
  },
  "warranty-pipe::warranty-closed": {
    title: "Claim closed",
    customer: "Replacement delivered; claim is done.",
    owner: "Service",
    system: "Warranty pipeline terminal; post-care may still fire.",
    dwell: "Same day as successful delivery",
    unlocks: "Registry + goodwill follow-up.",
    zone: "Warranty",
  },

  /* ── Exception storyKeys ── */
  "ncr-gate-a-fail": {
    title: "NCR — Gate A fail",
    customer: "Doesn’t hear this yet — quality stopped the traveler.",
    owner: "QC",
    system: "Weld/dim fail freezes the MO; no powder until remake passes.",
    dwell: "Hours (disposition) + days (rework)",
    unlocks: "Manufacturing mirror → Rejected, then weld remake.",
    zone: "QC",
  },
  "ncr-rejected": {
    title: "Manufacturing mirror — Rejected",
    customer: "Lead time may slip; service/sales get the truth from Ops.",
    owner: "Factory / Ops",
    system: "GHL mirror of Katana reject — Katana remains physical truth.",
    dwell: "Until NCR disposition",
    unlocks: "Rework at the failing station.",
    zone: "Manufacturing mirror",
  },
  "ncr-rework": {
    title: "Rework at weld",
    customer: "Waiting on a corrected frame.",
    owner: "Factory · Weld",
    system: "Same work center; traveler does not skip Gate A.",
    dwell: "Hours–days",
    unlocks: "Gate A re-inspect.",
    zone: "Shop floor",
  },
  "ncr-gate-a-pass": {
    title: "Gate A pass after remake",
    customer: "Quality is back on the happy path.",
    owner: "QC",
    system: "NCR closed at this gate; coating may proceed.",
    dwell: "Hours",
    unlocks: "Powder / remaining stations.",
    zone: "QC",
  },
  "ncr-cleared": {
    title: "NCR cleared — Ready for Delivery",
    customer: "Order can be scheduled again.",
    owner: "Factory / Logistics",
    system: "Mirror returns to Ready; logistics picks up.",
    dwell: "Days until route",
    unlocks: "Dispatch.",
    zone: "Manufacturing mirror",
  },
  "clover-miss-invoice": {
    title: "QBO invoice still posts",
    customer: "Will receive the invoice even if POS match is pending.",
    owner: "Finance",
    system: "V8 rule: Clover never blocks inv_${opportunity_id}.",
    dwell: "Minutes after Delivered",
    unlocks: "Clover fuzzy match attempt.",
    zone: "Treasury",
  },
  "clover-miss-dlq": {
    title: "Clover miss → DLQ",
    customer: "Deposit exists somewhere; books need a human match.",
    owner: "Finance",
    system: "Fuzzy match failed (amount/window/location). Unmatched job → DLQ. Invoice stays.",
    dwell: "Minutes now · hours–days to recon",
    unlocks: "Manual recon; Sales can still move to Delivered.",
    zone: "Treasury",
  },
  "clover-miss-delivered": {
    title: "CRM Delivered despite unmatched POS",
    customer: "Order is complete; finance recon is a back-office loop.",
    owner: "Sales / Finance",
    system: "Happy-path customer stage is not held hostage by Clover.",
    dwell: "Minutes",
    unlocks: "Post-care; recon continues off-stage.",
    zone: "Sales AZ",
  },
  "clover-miss-postcare": {
    title: "Post-care still starts",
    customer: "Care SMS / NPS should not wait on POS matching.",
    owner: "Marketing",
    system: "Post-care is customer lifecycle, not treasury close.",
    dwell: "Day 0 cadence",
    unlocks: "Reviews; finance DLQ is a parallel track.",
    zone: "Post-care",
  },
  "redis-failopen": {
    title: "Redis down — fail-open",
    customer: "Never sees this. Order must not stall.",
    owner: "Engineering",
    system: "L1 dedupe timeout/error is ignored; do not 500 the webhook.",
    dwell: "Timeout window (seconds)",
    unlocks: "Postgres outbox still records the event.",
    zone: "Dedupe",
  },
  "redis-failopen-outbox": {
    title: "Outbox is source of truth",
    customer: "Invisible.",
    owner: "Engineering",
    system: "Duplicate protection falls back to Postgres unique / saga — not Redis.",
    dwell: "Seconds",
    unlocks: "Inngest CCR lease.",
    zone: "State",
  },
  "redis-failopen-ccr": {
    title: "CCR still leases the job",
    customer: "Invisible.",
    owner: "Engineering",
    system: "Inngest sweeper + claim lease survive Redis absence.",
    dwell: "Seconds–retry minutes",
    unlocks: "Katana MO (idempotent).",
    zone: "Execution",
  },
  "redis-failopen-katana": {
    title: "Factory dispatch continues",
    customer: "MO is still created.",
    owner: "Factory / Engineering",
    system: "Idempotency-Key on Katana absorbs any duplicate retry after Redis recovers.",
    dwell: "Seconds",
    unlocks: "Work centers — same as happy path.",
    zone: "Factory API",
  },
  "gate-b-fail": {
    title: "NCR — Gate B DFT / adhesion fail",
    customer: "Lead time slips; finish must be stripped and redone.",
    owner: "QC · Coatings",
    system: "DFT or adhesion below spec; traveler frozen before upholstery.",
    dwell: "Hours (hold) + days (recoat queue)",
    unlocks: "Mirror → Rejected; blast + powder rework.",
    zone: "QC",
  },
  "gate-b-rejected": {
    title: "Manufacturing mirror — Rejected (coating)",
    customer: "Ops communicates revised ETA.",
    owner: "Factory / Ops",
    system: "Katana + GHL mirror show reject; upholstery will not start.",
    dwell: "Until recoat plan",
    unlocks: "Surface prep / blast station.",
    zone: "Manufacturing mirror",
  },
  "gate-b-rework": {
    title: "Blast & prep for recoat",
    customer: "Waiting on corrected finish.",
    owner: "Factory · Finishing",
    system: "Strip failed coat; prep for second powder pass.",
    dwell: "Hours–days",
    unlocks: "Powder coat retry.",
    zone: "Shop floor",
  },
  "gate-b-recoat": {
    title: "Second powder pass",
    customer: "Finish is being corrected.",
    owner: "Factory · Coatings",
    system: "Same traveler; Gate B must pass before sew/assembly.",
    dwell: "Hours–days + cure",
    unlocks: "Gate B re-inspect.",
    zone: "Shop floor",
  },
  "gate-b-pass": {
    title: "Gate B pass after recoat",
    customer: "Quality back on path.",
    owner: "QC",
    system: "Adhesion/DFT within spec; NCR closed at Gate B.",
    dwell: "Hours",
    unlocks: "Upholstery and assembly.",
    zone: "QC",
  },
  "gate-b-cleared": {
    title: "Ready for Delivery after coating NCR",
    customer: "Can be scheduled again.",
    owner: "Logistics",
    system: "Mirror → Ready; downstream same as happy path.",
    dwell: "Days until route",
    unlocks: "Dispatch.",
    zone: "Manufacturing mirror",
  },
  "qbo-mutex-first": {
    title: "First Delivered → QBO invoice",
    customer: "Receives invoice for completed delivery.",
    owner: "Finance",
    system: "OAuth token + mutex around QBO write for franchise entity.",
    dwell: "Minutes (systems)",
    unlocks: "Second concurrent Delivered event queues.",
    zone: "Treasury",
  },
  "qbo-mutex-blocked": {
    title: "QBO mutex — second invoice waits",
    customer: "Second customer still gets invoice — just not in the same second.",
    owner: "Finance / Engineering",
    system: "Mutex lease held by first inv_${opportunity_id}; second job retries with backoff.",
    dwell: "Seconds–minutes (never hours)",
    unlocks: "Retry when mutex releases.",
    zone: "Treasury",
  },
  "qbo-mutex-retry": {
    title: "Mutex released — second invoice posts",
    customer: "Both invoices issued; Clover match proceeds independently.",
    owner: "Finance",
    system: "Same mutex pattern; Clover miss still never blocks invoice.",
    dwell: "Minutes",
    unlocks: "Clover fuzzy match per order.",
    zone: "Treasury",
  },
  "gate-c-fail": {
    title: "Gate C fail — fit / finish / photo miss",
    customer: "Pre-pack hold; delivery date may move.",
    owner: "QC",
    system: "360° photo log or fit check failed; NCR before ship.",
    dwell: "Hours (disposition)",
    unlocks: "Rejected mirror → re-upholster or frame adjust.",
    zone: "QC",
  },
  "gate-c-rejected": {
    title: "Manufacturing mirror — Rejected (pre-pack)",
    customer: "Ops resets ETA.",
    owner: "Factory / QC",
    system: "GHL mirror Rejected; upholstery/assembly frozen.",
    dwell: "Until rework plan",
    unlocks: "Re-upholster / frame adjust (+2d SLA penalty).",
    zone: "Manufacturing mirror",
  },
  "gate-c-rework": {
    title: "Re-upholster / frame adjust",
    customer: "Waiting on corrected fit and finish.",
    owner: "Factory · Soft goods / Assembly",
    system: "Gate C failure remediation; +2 calendar-day SLA penalty.",
    dwell: "+2 days penalty",
    unlocks: "Re-assembly → Gate C re-inspect.",
    zone: "Shop floor",
  },
  "gate-c-reassembly": {
    title: "Final assembly (second pass)",
    customer: "Suite rebuilt after QC hold.",
    owner: "Factory · Assembly",
    system: "Traveler re-enters Gate C photo log.",
    dwell: "Hours–days",
    unlocks: "Gate C re-inspect.",
    zone: "Shop floor",
  },
  "gate-c-pass": {
    title: "Gate C pass — pre-pack cleared",
    customer: "Quality locked; ship window reopens.",
    owner: "QC",
    system: "Photo log attached; NCR closed.",
    dwell: "Hours",
    unlocks: "Ready for Delivery.",
    zone: "QC",
  },
  "gate-c-cleared": {
    title: "Ready for Delivery after Gate C NCR",
    customer: "Can be scheduled again.",
    owner: "Logistics",
    system: "Mirror → Ready; route scheduling resumes.",
    dwell: "Per SLA route phase (+3d)",
    unlocks: "Dispatch.",
    zone: "Manufacturing mirror",
  },
  "ccr-dual-webhook": {
    title: "Dual webhook — GHL network retry",
    customer: "Invisible — must not create two factory orders.",
    owner: "Engineering",
    system: "Two simultaneous POSTs hit Ingress for the same Produce FO.",
    dwell: "Milliseconds apart",
    unlocks: "Postgres CCR lease arbitration.",
    zone: "Edge",
  },
  "ccr-worker1-lease": {
    title: "Worker 1 — mo_create lease acquired",
    customer: "Invisible.",
    owner: "Engineering",
    system: "FOR UPDATE claim in Postgres; Worker 1 owns the saga.",
    dwell: "Seconds",
    unlocks: "Inngest dispatch to Katana.",
    zone: "State",
  },
  "ccr-webhook-retry": {
    title: "Worker 2 — duplicate webhook arrives",
    customer: "Invisible.",
    owner: "Engineering",
    system: "Second GHL retry enters Ingress while Worker 1 is in-flight.",
    dwell: "Same second",
    unlocks: "UniqueViolation / lease check.",
    zone: "Edge",
  },
  "ccr-worker2-violation": {
    title: "Worker 2 — 23505 + CCR_LEASE_ACTIVE",
    customer: "Invisible.",
    owner: "Engineering",
    system: "UniqueViolation on claim; sees active lease → yields (CCR_LEASE_ACTIVE).",
    dwell: "Seconds (yield)",
    unlocks: "Backoff — no second MO.",
    zone: "State",
  },
  "ccr-worker1-inngest": {
    title: "Worker 1 — Inngest executes MO create",
    customer: "Invisible.",
    owner: "Engineering",
    system: "CCR lease holder runs Katana Idempotency-Key path.",
    dwell: "Seconds",
    unlocks: "katana_mo_id persisted.",
    zone: "Execution",
  },
  "ccr-worker1-katana": {
    title: "Worker 1 — Katana MO written",
    customer: "One physical job — exactly once.",
    owner: "Factory / Engineering",
    system: "MO id written to saga row; Manufacturing mirror follows.",
    dwell: "Seconds",
    unlocks: "Worker 2 duplicate resolution.",
    zone: "Factory API",
  },
  "ccr-worker2-yield": {
    title: "Worker 2 — backoff wake",
    customer: "Invisible.",
    owner: "Engineering",
    system: "Retry after lease TTL; reads existing katana_mo_id.",
    dwell: "Seconds–minutes",
    unlocks: "Safe duplicate terminate.",
    zone: "State",
  },
  "ccr-duplicate-resolve": {
    title: "Worker 2 — duplicate safely resolved",
    customer: "Never sees a double build.",
    owner: "Engineering",
    system: "katana_mo_id present → idempotent complete, no second MO.",
    dwell: "Seconds",
    unlocks: "Happy factory path continues.",
    zone: "Execution",
  },

  /* Executive lifecycle map — Node 1→12 */
  "lc-ingress": {
    title: "Orders enter from every channel",
    customer: "Completes checkout on Woo or signs in GHL.",
    owner: "Engineering",
    system: "WooCommerce + GHL webhooks POST to /api/webhooks/* with signed payloads.",
    dwell: "Instant",
    unlocks: "Normalized event in incoming_webhooks queue.",
    zone: "Digital Ingress",
  },
  "lc-hmac": {
    title: "Trust boundary — verify before parse",
    customer: "Invisible security gate.",
    owner: "Engineering",
    system: "HMAC-SHA256 signature check; rejects replay/tamper; canonical JSON shape.",
    dwell: "Milliseconds",
    unlocks: "Idempotent webhook row ready for workers.",
    zone: "Digital Ingress",
  },
  "lc-inngest": {
    title: "Durable async orchestration",
    customer: "Invisible — no blocking on the HTTP response.",
    owner: "Engineering",
    system: "Inngest fan-out: validate → enrich → route to PIM/Katana handlers.",
    dwell: "Seconds",
    unlocks: "SKU resolution job on the worker pool.",
    zone: "Middleware",
  },
  "lc-pim": {
    title: "Global SKU dictionary match",
    customer: "Product config resolves to real materials & FG SKUs.",
    owner: "PIM / Ops",
    system: "sku_mappings join — rejects unknown SKUs before MRP release.",
    dwell: "Seconds",
    unlocks: "Validated line items for Katana Sales Order.",
    zone: "Middleware",
  },
  "lc-sales-order": {
    title: "Katana Sales Order created",
    customer: "Order is officially in production planning.",
    owner: "Ops / Sales support",
    system: "Katana REST — SO from validated SKUs, customer, due date.",
    dwell: "Minutes",
    unlocks: "BOM explosion against raw_materials_catalog.",
    zone: "MRP",
  },
  "lc-bom": {
    title: "Materials allocated from BOM",
    customer: "Build kit is reserved on the floor.",
    owner: "Production planning",
    system: "product_bom → fabrics, extrusions, powder, consumables reserved.",
    dwell: "Minutes",
    unlocks: "Manufacturing Order with component demand.",
    zone: "MRP",
  },
  "lc-mo": {
    title: "Manufacturing Order released",
    customer: "Job hits the shop schedule.",
    owner: "Production manager",
    system: "Katana MO with routing, work centers, and promised ship date.",
    dwell: "Hours",
    unlocks: "WIP on aluminum fabrication line.",
    zone: "MRP",
  },
  "lc-aluminum": {
    title: "Aluminum cut & mechanical joinery",
    customer: "Frame takes shape — no weld distortion.",
    owner: "Fabrication pod",
    system: "Chop saw → tack-free mechanical joints per cut list.",
    dwell: "1–2 days",
    unlocks: "Bare frame to surface treatment.",
    zone: "Shop Floor",
  },
  "lc-surface": {
    title: "Sublimation & powder coat",
    customer: "Color and finish locked to spec.",
    owner: "Finishing",
    system: "Sandblast prep → sublimation print or powder cure oven cycle.",
    dwell: "1–3 days",
    unlocks: "Cured frame to upholstery.",
    zone: "Shop Floor",
  },
  "lc-upholstery": {
    title: "Textile cut & sew",
    customer: "Cushions and slings match the approved swatch.",
    owner: "Upholstery",
    system: "Fabric from raw_materials_catalog → cut → sew → cushion build.",
    dwell: "1–2 days",
    unlocks: "Soft goods ready for final marriage.",
    zone: "Shop Floor",
  },
  "lc-qa": {
    title: "Final assembly & quality gate",
    customer: "Product matches showroom promise.",
    owner: "QC lead",
    system: "Hardware torque, fit check, photo sign-off before pack.",
    dwell: "Hours",
    unlocks: "Release to logistics.",
    zone: "Shop Floor",
  },
  "lc-logistics": {
    title: "Ship + invoice close",
    customer: "Receives delivery; accounting is clean.",
    owner: "Logistics / Finance",
    system: "Dispatch route → delivery confirm → QBO invoice webhook trigger.",
    dwell: "Days",
    unlocks: "Revenue recognized · post-care lifecycle.",
    zone: "Logistics & Treasury",
  },
};

export function getStory(
  nodeId: string,
  stageId?: string | null,
  journeyId?: JourneyId | null,
  storyKey?: string | null
): StoryCard | null {
  if (storyKey && STORIES[storyKey]) return STORIES[storyKey];
  if (journeyId && stageId) {
    const jk = `${journeyId}::${key(nodeId, stageId)}`;
    if (STORIES[jk]) return STORIES[jk];
  }
  if (journeyId) {
    const jn = `${journeyId}::${nodeId}`;
    if (STORIES[jn]) return STORIES[jn];
  }
  if (stageId) {
    const k = key(nodeId, stageId);
    if (STORIES[k]) return STORIES[k];
  }
  return STORIES[nodeId] ?? null;
}

/** Fallback card while a step has no authored story yet */
export function fallbackStory(
  nodeId: string,
  stageId?: string | null
): StoryCard {
  return {
    title: stageId ? `${nodeId} · ${stageId}` : nodeId,
    customer: "Add customer-facing language as you gather ops detail.",
    owner: "TBD",
    system: "Node is live on the Full Map — enrich this story anytime.",
    dwell: "—",
    unlocks: "Next sequence step.",
    zone: "Full Map",
  };
}
