import * as fs from 'fs';
import * as path from 'path';

// Paths
const ghlSchemaPath = path.resolve(__dirname, '../docs/blueprints/GHL_Data_Schema.md');
const katanaSchemaPath = path.resolve(__dirname, '../docs/blueprints/Katana_Data_Schema.md');
const outputPath = path.resolve(__dirname, '../topology/src/config/liveIds.ts');

function extractMarkdownTable(content: string, headerStart: string): string[] {
  const lines = content.split('\n');
  const result: string[] = [];
  let inTable = false;
  
  for (const line of lines) {
    if (line.includes(headerStart)) {
      inTable = true;
      continue;
    }
    if (inTable) {
      if (line.trim() === '' && result.length > 0) {
        break; // end of table
      }
      if (line.includes('|')) {
        result.push(line);
      }
    }
  }
  return result;
}

function parseGHL() {
  if (!fs.existsSync(ghlSchemaPath)) return {};
  const content = fs.readFileSync(ghlSchemaPath, 'utf8');
  
  // Extract Stage UUIDs
  const stageLines = extractMarkdownTable(content, '| Pipeline | Stage Name | Stage UUID |');
  const stages: Record<string, string> = {};
  stageLines.forEach(line => {
    const parts = line.split('|').map(s => s.trim()).filter(Boolean);
    if (parts.length >= 3 && !parts[0].includes('---')) {
      const pipeline = parts[0];
      const uuidMatch = parts[2].match(/`([^`]+)`/);
      if (uuidMatch) {
        if (pipeline.includes('AZ')) stages['AZ_GATE_1'] = uuidMatch[1];
        if (pipeline.includes('CA')) stages['CA_GATE_1'] = uuidMatch[1];
      }
    }
  });

  // Extract Pipelines
  const pipelineLines = extractMarkdownTable(content, '| Pipeline Name | Pipeline ID |');
  const pipelines: Record<string, string> = {};
  pipelineLines.forEach(line => {
    const parts = line.split('|').map(s => s.trim()).filter(Boolean);
    if (parts.length >= 2 && !parts[0].includes('---')) {
      const name = parts[0];
      const idMatch = parts[1].match(/`([^`]+)`/);
      if (idMatch) {
        pipelines[name.replace(/[^a-zA-Z0-9]/g, '_')] = idMatch[1];
      }
    }
  });

  return { stages, pipelines };
}

function parseKatana() {
  if (!fs.existsSync(katanaSchemaPath)) return {};
  const content = fs.readFileSync(katanaSchemaPath, 'utf8');
  // Currently empty based on blueprint, returning placeholder
  return {
    raw: content.length > 0 ? "Present" : "Empty"
  };
}

function main() {
  console.log('Syncing live IDs from blueprints to topology...');
  const ghlData = parseGHL();
  const katanaData = parseKatana();

  const output = `// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by scripts/sync-topology-nodes.ts

export const LIVE_IDS = {
  GHL: ${JSON.stringify(ghlData, null, 2)},
  KATANA: ${JSON.stringify(katanaData, null, 2)}
};
`;

  // Create dir if not exists
  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(outputPath, output, 'utf8');
  console.log(\`Successfully synced live IDs to \${outputPath}\`);
}

main();
